### ISSUE TITLE
Pull in tree from devtools 

### ISSUE THREAD

**Issue by w-jiang** [gregtatum/z-index-devtool#29]
- https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components
- Change 'require' of line 7 in tree.js to 'react' instead of 'devtools/client/shared/vendor/react'

**Comment by jreinlein** [comment]
https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components/tree.js :smiley:

**Comment by jreinlein** [comment]
Example of usage (seen in FF Nightly): https://dxr.mozilla.org/mozilla-central/source/devtools/client/performance/components/waterfall-tree.js

**Comment by jreinlein** [comment]
As per @gregtatum,   This is what the structure should look like:

```
  <StackingContextTree>
    <Tree>
      <TreeItem>
      <TreeItem>
      <TreeItem>
    </Tree>
  </StackingContextTree>  
```

**Comment by jreinlein** [comment]
Completed in PR #55
