### ISSUE TITLE
Properly overlay a Canvas element over selected DOM node

### ISSUE THREAD

**Issue by jreinlein** [gregtatum/z-index-devtool#54]
Our last implementation would add/remove a CSS class to the DOM node, and CSS would add a border.

Rather, let's implement a canvas element overlaying the DOM node that is selected in the tree.

**Comment by jreinlein** [comment]
Note: the following link may be of help:

https://gist.github.com/sebmarkbage/6f7da234174ab9f64cce

**Comment by bkindersley** [comment]
i found there was weirdness with the sizing of the canvas.

i ended up using a div that is rerendered on scroll/resize etc.

closing this issue.
