### ISSUE TITLE
dom-container z-index is causing divs in the example HTMLs with negative z-order to be hidden

### ISSUE THREAD

**Issue by w-jiang** [gregtatum/z-index-devtool#66]
dom-container z-index is not being set (aka. "auto" which is the same z-order as 0) which causes divs in the html examples that have a negative z-order to be hidden under the dom-container.

While it's easy to just make the dom-container z-order to be -99999, it is a code smell and I think we should address the underlying problem of our container and how we're inserting our HTML files into it. A CSS style in the html should only apply to the html and not the sidebar (.div{} affects all the divs, even in the sidebar)

**Comment by w-jiang** [comment]
@gregtatum This might not be in scope for our prototype... if its not, I can just apply the quick fix and set the dom-container to a large negative value

**Comment by gregtatum** [comment]
Off the top of my head you might be able to set the dom-container to have position: relative. I'd say if you put in the -99999 value then at least include a comment about what you're doing.

**Comment by w-jiang** [comment]
This is resolved with Bria's fix of the dom-container!
