### ISSUE TITLE
Nov 22

### ISSUE THREAD

**Issue by gregtatum** [gregtatum/z-index-devtool#72]
We should compute the correct stacking context tree: e.g.

- [x] Mouseover on entire row, show highlighter. (bria)
- [x] Hide button using Greg's css rule (James)
- [ ] Get more test coverage. (James)
- [x] Add some padding to bottom details panel (wenny)
- [x] (Stretch) Add element picker (wenny)
- [x] Fix the issue that squishes the tree's rows when there are too many to fit on screen

Present at DevTools meeting at 9am pacific on Tuesday Nov 29th
https://wiki.mozilla.org/DevTools

**Comment by jreinlein** [comment]
(added the squishing issue)

**Comment by jreinlein** [comment]
Tests to implement, as far as I can think:

- [ ] selecting a node
- [ ] highlighting an element (mouse over)
- [ ] computing a bounding rect
- [x] toggle node -> test whether it expands or collapses appropriately
- [ ] picker button
