### ISSUE TITLE
Element Selection and Hover Conflict

### ISSUE THREAD

**Issue by w-jiang** [gregtatum/z-index-devtool#80]
If I select an element in the dom, the selected element highlight goes away when I hover over any node in the stacking context. When I stop hovering over elements, I think it should go back to displaying the previously selected element.

Expected behaviour is open for discussion

**Comment by jreinlein** [comment]
I like it the way it is right now, honestly. Otherwise _the user has no way of deselecting_. 

Yes, it's a hassle if you don't mean to change your selection and accidentally hover over other elements, but I don't think it's that bad.

Mull it over, and let's talk about it at our next meeting :)
